name: Versioning

on:
  push:
    branches: [release/**, hotfix/**]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '6.x'
          
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        
      - name: Output version
        run: echo "NuGetVersionV2=${{ steps.gitversion.outputs.nuGetVersionV2 }}"
        
#      - name: Output version 2
#        run: echo "Calculated version: ${{ steps.gitversion.outputs.semVer }}"